urls:
  api: 'https://api.multiversx.com'
  swagger:
    - 'https://microservice.multiversx.com'
    - 'https://devnet-microservice.multiversx.com'
    - 'https://testnet-microservice.multiversx.com'
features:
  publicApi:
    enabled: true
    port: 3000
  privateApi:
    enabled: true
    port: 4000
  keepAliveAgent:
    enabled: true
  swap:
    enabled: true
    cron: '* * * * *'
nativeAuth:
  maxExpirySeconds:
  acceptedOrigins:
    - utils.multiversx.com
security:
  admins:
rateLimiterSecret:
keepAliveTimeout:
  downstream: 61000
  upstream: 60000
useCachingInterceptor: false
redis:
  host: '127.0.0.1'
  port: 6379
  username:
  password: ''
  tls: false
globalPrefix: ''
redlock:
  keyExpiration: 60000
  maxRetries: 50
  retryInterval: 1000
paymaster:
  contractAddress:
  gasLimit: 10000000
relayer:
  address:
  pemFilePath:
  name:
wrappedEGLDIdentifier:
tokens:
