urls:
  api: 'https://devnet-api.multiversx.com'
  swagger:
    - 'https://devnet-microservice.multiversx.com'
    - 'https://testnet-microservice.multiversx.com'
    - 'https://microservice.multiversx.com'
  redis: '127.0.0.1'
database:
  host: 'localhost'
  port: 3306
  username: 'root'
  password: 'root'
  name: 'paymaster'
features:
  publicApi:
    enabled: true
    port: 3000
  privateApi:
    enabled: true
    port: 4000
  keepAliveAgent:
    enabled: true
nativeAuth:
  maxExpirySeconds:
  acceptedOrigins:
    - utils.multiversx.com
security:
  admins:
rateLimiterSecret:
keepAliveTimeout:
  downstream: 61000
  upstream: 60000
useCachingInterceptor: false
paymaster:
  contractAddress: 'erd1qqqqqqqqqqqqqpgqm0lf822t2w0ly66hg27kycuk4w0guzn43hvqf28p8w'
  gasLimit: 10000000
relayer:
  address: 'erd1rwsq0fxjrce9955hvvl3qrpl96xmuuxch9m6wlhxx6zs0n2v3hvqyu4lm5'
  pemFile: 'relayerWallet.pem'
  flatFeeEGLD: '9000000000000000'
