urls:
  api: ${API_URL}
  swagger:
    - 'https://devnet-tools.multiversx.com/paymaster'
    - 'https://testnet-tools.multiversx.com/paymaster'
features:
  publicApi:
    enabled: true
    port: 3000
  privateApi:
    enabled: true
    port: 4000
  keepAliveAgent:
    enabled: true
  swap:
    enabled: true
    cron: '* * * * *'
nativeAuth:
  maxExpirySeconds:
  acceptedOrigins:
    - utils.multiversx.com
security:
  admins: ${SECURITY_ADMINS}
rateLimiterSecret: ${RATE_LIMITER_SECRET}
keepAliveTimeout:
  downstream: 61000
  upstream: 60000
useCachingInterceptor: false
redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  username: ${REDIS_USERNAME}
  password: ${REDIS_PASSWORD}
  tls: ${REDIS_TLS}
globalPrefix: ''
redlock:
  keyExpiration: 60000
  maxRetries: 50
  retryInterval: 1000
paymaster:
  contractAddress:
    shard0:
    shard1:
    shard2:
  gasLimit: 10000000
relayer:
  pemFilePath: 'apps/api/wallets/relayerWallet_3.pem'
  name:
wrappedEGLDIdentifier:
tokens:
