urls:
  api: ${API_URL}
  swagger:
    - 'https://testnet-tools.multiversx.com/paymaster'
    - 'https://devnet-tools.multiversx.com/paymaster'
features:
  publicApi:
    enabled: true
    port: ${num:PUBLIC_API_PORT}
  privateApi:
    enabled: true
    port: ${num:PRIVATE_API_PORT}
  keepAliveAgent:
    enabled: true
  swap:
    enabled: false
    cron: '* * * * *'
    port: ${num:AUTO_SWAP_PORT}
  drainProtection:
    enabled: true
    cron: '*/20 * * * * *'
    port: ${num:DRAIN_PROTECTION_PORT}
    addressIntervalInMinutes: 120
    addressMaxFailedTxsPerInterval: 5 
    totalIntervalInMinutes: 10
    totalMaxFailedTxsPerInterval: 10 
nativeAuth:
  maxExpirySeconds:
  acceptedOrigins:
    - utils.multiversx.com
security:
  admins: ${arr:SECURITY_ADMINS}
rateLimiterSecret: ${RATE_LIMITER_SECRET}
keepAliveTimeout:
  downstream: 61000
  upstream: 60000
useCachingInterceptor: false
redis:
  host: ${PM_REDIS_HOST}
  port: ${num:PM_REDIS_PORT}
  username: ${PM_REDIS_USERNAME}
  password: ${PM_REDIS_PASSWORD}
  tls: ${bool:PM_REDIS_TLS}
globalPrefix: ${GLOBAL_PREFIX}
redlock:
  keyExpiration: 60000
  maxRetries: 50
  retryInterval: 1000
paymaster:
  contractAddress:
    shard0: 'erd1qqqqqqqqqqqqqpgq5jzvqr98xya5m4ce0cvmz60wpuqhe6u7nk6qcl9ftm'
    shard1: 'erd1qqqqqqqqqqqqqpgqcfsatn0uud782nrkk230aq4dwmgtdhpys3ssu5nvzk'
    shard2: 'erd1qqqqqqqqqqqqqpgq34p72qjp8rdut5kewtpde8fa5yu7hpz7dheqetm3ks'
  gasLimit: 10000000
relayer:
  pemFilePath: ${RELAYER_PEM_PATH}
  name:
wrappedEGLDIdentifier: 'WEGLD-dd8471'
tokens:
  - USDC-5bee92:
      feePercentage: 3
      feeAmount: '10000'
  - RIDE-d3a377:
      feePercentage: 5
      feeAmount: '0'
      swapContract: 'erd1qqqqqqqqqqqqqpgqzt7clww7329ajkq07x295h7hvl2hgnsaexks5m7sen'
      swapParameters: 'swapTokensFixedInput@WEGLD-dd8471@01'
      swapMinAmount: '2000000000000000000'
      swapGasLimit: 12050000
  - WEGLD-dd8471:
      feePercentage: 5
      feeAmount: '0'
      swapContract: 'erd1qqqqqqqqqqqqqpgqhpmz3gh6jnwuyw4qxnksfh74tv8kdf6gexksrputsf'
      swapParameters: 'unwrapEgld'
      swapMinAmount: '50000000000000000'
      swapGasLimit: 4200000
  - UTK-f4e83f:
      feePercentage: 5
      feeAmount: '1000000'
      swapContract: 'erd1qqqqqqqqqqqqqpgqluxegqj5fymplf8vj3qen6ryh03dukhxexks43z5kc'
      swapParameters: 'swapTokensFixedInput@WEGLD-dd8471@01'
      swapMinAmount: '1000000000000'
      swapGasLimit: 12050000