urls:
  api: 'https://api.multiversx.com'
  swagger:
    - 'https://microservice.multiversx.com'
    - 'https://devnet-microservice.multiversx.com'
    - 'https://testnet-microservice.multiversx.com'
  redis: '127.0.0.1'
database:
  host: 'localhost'
  port: 3306
  username: 'root'
  password: 'root'
  name: 'paymaster'
features:
  publicApi:
    enabled: true
    port: 3000
  privateApi:
    enabled: true
    port: 4000
  keepAliveAgent:
    enabled: true
nativeAuth:
  maxExpirySeconds:
  acceptedOrigins:
    - utils.multiversx.com
security:
  admins:
rateLimiterSecret:
keepAliveTimeout:
  downstream: 61000
  upstream: 60000
useCachingInterceptor: false
paymaster:
  contractAddress:
  gasLimit: 10000000
relayer:
  address:
  pemFilePath:
  flatFeeEGLD: '9000000000000000'
wrappedEGLDIdentifier:
