urls:
  api: ${API_URL}
  swagger:
    - 'https://devnet-tools.multiversx.com/paymaster'
    - 'https://testnet-tools.multiversx.com/paymaster'
features:
  publicApi:
    enabled: true
    port: ${num:PUBLIC_API_PORT}
  privateApi:
    enabled: true
    port: ${num:PRIVATE_API_PORT}
  keepAliveAgent:
    enabled: true
  swap:
    enabled: true
    cron: '* * * * *'
    port: ${num:AUTO_SWAP_PORT}
  drainProtection:
    enabled: true
    cron: '*/20 * * * * *'
    port: ${num:DRAIN_PROTECTION_PORT}
    addressIntervalInMinutes: 120
    addressMaxFailedTxsPerInterval: 5 
    totalIntervalInMinutes: 10
    totalMaxFailedTxsPerInterval: 10 
nativeAuth:
  maxExpirySeconds:
  acceptedOrigins:
    - utils.multiversx.com
security:
  admins: ${arr:SECURITY_ADMINS}
rateLimiterSecret: ${RATE_LIMITER_SECRET}
keepAliveTimeout:
  downstream: 61000
  upstream: 60000
useCachingInterceptor: false
redis:
  host: ${PM_REDIS_HOST}
  port: ${num:PM_REDIS_PORT}
  username: ${PM_REDIS_USERNAME}
  password: ${PM_REDIS_PASSWORD}
  tls: ${bool:PM_REDIS_TLS}
globalPrefix: ${GLOBAL_PREFIX}
redlock:
  keyExpiration: 60000
  maxRetries: 50
  retryInterval: 1000
paymaster:
  contractAddress:
    shard0:
    shard1:
    shard2:
  gasLimit: 10000000
relayer:
  pemFilePath: ${RELAYER_PEM_PATH}
  name:
wrappedEGLDIdentifier:
tokens:
