urls:
  api: ${API_URL}
  swagger:
    - 'https://testnet-tools.multiversx.com/paymaster'
    - 'https://devnet-tools.multiversx.com/paymaster'
features:
  publicApi:
    enabled: true
    port: ${num:PUBLIC_API_PORT}
  privateApi:
    enabled: true
    port: ${num:PRIVATE_API_PORT}
  keepAliveAgent:
    enabled: true
  swap:
    enabled: false
    cron: '* * * * *'
    port: ${num:AUTO_SWAP_PORT}
  drainProtection:
    enabled: true
    cron: '*/20 * * * * *'
    port: ${num:DRAIN_PROTECTION_PORT}
    addressIntervalInMinutes: 120
    addressMaxFailedTxsPerInterval: 5 
    totalIntervalInMinutes: 10
    totalMaxFailedTxsPerInterval: 10 
nativeAuth:
  maxExpirySeconds:
  acceptedOrigins:
    - utils.multiversx.com
security:
  admins: ${arr:SECURITY_ADMINS}
rateLimiterSecret: ${RATE_LIMITER_SECRET}
keepAliveTimeout:
  downstream: 61000
  upstream: 60000
useCachingInterceptor: false
redis:
  host: ${REDIS_HOST}
  port: ${num:REDIS_PORT}
  username: ${REDIS_USERNAME}
  password: ${REDIS_PASSWORD}
  tls: ${bool:REDIS_TLS}
globalPrefix: ${GLOBAL_PREFIX}
redlock:
  keyExpiration: 60000
  maxRetries: 50
  retryInterval: 1000
paymaster:
  contractAddress:
    shard0: 'erd1qqqqqqqqqqqqqpgqar3ap4jzj5zq5km9mezltz63kx4axgxqnk6qzvgxpk'
    shard1: 'erd1qqqqqqqqqqqqqpgqmvwpu8qx4c3umveamvswmuuxhf5lsmj5s3ssrhh2ed'
    shard2: 'erd1qqqqqqqqqqqqqpgq0hdtg9mwf4hec826ykpdunl06885akw9dheq9n2unq'
  gasLimit: 10000000
relayer:
  pemFilePath: ${RELAYER_PEM_PATH}
  name:
wrappedEGLDIdentifier: 'WEGLD-01e49d'
tokens:
  - USDC-f89dfe:
      feePercentage: 3
      feeAmount: '10000'
  - RIDE-3954e7:
      feePercentage: 5
      feeAmount: '0'
      swapContract: 'erd1qqqqqqqqqqqqqpgq5dkvkrn56yrgavwx8fm9ld9eqj07g7ps295qchle4z'  #shard0
      swapParameters: 'swapTokensFixedInput@WEGLD-01e49d@01'
      swapMinAmount: '2000000000000000000'
      swapGasLimit: 12050000
  - WEGLD-01e49d:
      feePercentage: 5
      feeAmount: '0'
      swapContract: 'erd1qqqqqqqqqqqqqpgqfy4z88duqdusaksn399f4dny527m6xe07h0sll0m2t'
      swapParameters: 'unwrapEgld'
      swapMinAmount: '50000000000000000'
      swapGasLimit: 4200000
  - ASH-3538e0:
      feePercentage: 5
      feeAmount: '1000000'
      swapContract: 'erd1qqqqqqqqqqqqqpgq64cxskker47fd9spaetc6vylt2c3kmm7295qx2hu6j'
      swapParameters: 'swapTokensFixedInput@WEGLD-01e49d@01'
      swapMinAmount: '50000000000000000'
      swapGasLimit: 12050000
  - ITHEUM-471743:
      feePercentage: 5
      feeAmount: '1000000'
      swapContract: 'erd1qqqqqqqqqqqqqpgqkdxw8ewquxtt64t8rmdgqz3ja0zjycfm295qpdm8at'
      swapParameters: 'swapTokensFixedInput@WEGLD-01e49d@01'
      swapMinAmount: '1000000000000'
      swapGasLimit: 12050000